name: publish jitpack package
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish to JitPack
          run: |
            # Get the version from the release tag name
            version=${{ github.event.release.tag_name }}
            
            # Update the version in build.gradle
            sed -i "s/version = '.*'/version = '$version'/" build.gradle
            
            # Publish to JitPack
            ./gradlew clean build publish